name: Python Code Checks

permissions:
  contents: read

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pip
          key: uv-cache-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            uv-cache-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install uv
          uv sync

      - name: Run Ruff (PEP 8 Formatting)
        run: |
          source .venv/bin/activate
          make format

      - name: Run Ruff (Linting + Docstrings)
        run: |
          source .venv/bin/activate
          make check

      - name: Run vulture (Duplicate Code)
        run: |
          source .venv/bin/activate
          make vulture

      - name: Run xenon (Cyclomatic Complexity)
        run: |
          source .venv/bin/activate
          make xenon

      - name: Run pyright (Type Checking)
        run: |
          source .venv/bin/activate
          make pyright

      - name: Run pytest (Test Suite)
        run: |
          source .venv/bin/activate
          make test
